### ISSUE TITLE
Multi-platform: Create data layer plan

### ISSUE THREAD

**Issue by jbonisteel** [ooni/probe-multiplatform#24]
Create a plan for the data layer for multi-platform application, including:  

- Database schema
- Preferences schema

**Comment by aanorbel** [comment]
@sdsantos  any thoughts.

**Comment by sdsantos** [comment]
Looks good. We should match the existing schema as much as possible, to simplify the update/migration.

Is there a reason Network is a separate table? Were we planning on having something else link to it?

Measurement is the table we could drop right? If we show the measurement results from the web?

And if we drop Measurement, we can drop the URLs for now. Maybe later we want to cache them like Arturo said, tied to the test eventually, but that's a new feature.

**Comment by aanorbel** [comment]
## Network
- Network summary is displayed at the level of result list. 
- From engine events, `status.geoip_lookup` provides the information to save.
- The information is displayed in a couple of other places.

## Measurements.
- For now we would still have the measurements table. To display top level list of measurements while the further details go to the web.
- With the above, `Url` will be maintained for now.

**Comment by sdsantos** [comment]
If the Network is only stored in a 1-1 relation with Result, then it could be inside the Result table. But if it's actually a 1-N relation, or if we're planning to store Network data for other tables, then it needs to be a separate table.

Regarding the Measurement, do we need to keep all those fields? The screen we're switching to the web is only related with the JSON field we parse?

**Comment by aanorbel** [comment]
We only do a geoIP lookup when the test starts. Then engine is unaware if the network changes while the test has already started. This is a limitation we are aware of. To solve this issue, we need to maintain a 1-N relationship between Result and Network.

**Comment by sdsantos** [comment]
> We only do a geoIP lookup when the test starts. Then engine is unaware if the network changes while the test has already started. This is a limitation we are aware of. To solve this issue, we need to maintain a 1-N relationship between Result and Network.

Just noticed that the relationship is the other way around. The Network can have multiple results, but the Result can have only 1 network. That seems opposite of what you said.

**Comment by aanorbel** [comment]
Sorry for the mix up.  Multiple results can be gotten on a network.
