### ISSUE TITLE
NMS iOS: Unsure if app continues to run tests in background

### ISSUE THREAD

**Issue by jbonisteel** [ooni/probe-multiplatform#250]
I am unsure if tests are continuing to run when I put the app in the background. See the attached screen recording.

Steps to reproduce:

- Open NMS and initiate a test
- Navigate to a different app for a while (in the recording, I go check out the news app for a little bit)
- Come back to NMS app and the time hasn't really decreased

So I am not sure if it is just the tests are really slow or if something is happening and they pause while I use a different app. I have tried testing this multiple times with tests that take longer and have left the NMS app in the background for longer with the same results. If someone could also test this and verify if it is working as intended or if, indeed, there is a bug - that would be great!

https://github.com/user-attachments/assets/09ef0b5d-48c3-4411-9ef6-2b5f6be569d6

**Comment by aanorbel** [comment]
I can confirm there is a bug here. The tests seem to be paused till the user resumes the app. Looking into the issue
