### ISSUE TITLE
NMS Android: App in some sort of stuck state

### ISSUE THREAD

**Issue by jbonisteel** [ooni/probe-multiplatform#255]
TBH, I am not 100% sure how I managed to make this happen, but I was using the NMS Android app and I was testing out stopping a test in progress. See the link below for a screen recording. The app seems to get "stuck" in this perma link loading/testing running state. As you will see in the recording, I tried stopping the test but nothing happens. It looks like maybe there was both a manual test and an autorun happening at the same time? I wonder if that could have created some kind of conflict. I had to force-stop the app to get it out of this state. 

https://photos.app.goo.gl/YK4aoN5thW7pzGbt8

Also worth noting, maybe this would happen in iOS too but the autorun doesn't work for me so can't test what happens if both manual and autorun are happening at the same time.

**Comment by sdsantos** [comment]
- [ ] Background uploading should also support Stop
- [ ] Detect if an auto-run is running when the app starts, and update the TestState accordingly
- [ ] See if we can improve the descriptor update performance

**Comment by jbonisteel** [comment]
I have been trying to reproduce this, haven't been able to exactly reproduce what I saw in the screen recording. Some observations to add:

- If I have a test running, and I tap around other parts of the UI/Nav (results, settings) in general there is quite a lag/delay in the UI. I don't see this same lag when using iOS.

**Comment by sdsantos** [comment]
Most of the lagginess should be fixed by this PR: https://github.com/ooni/probe-multiplatform/pull/272
