### ISSUE TITLE
NMS Android: UI glitch

### ISSUE THREAD

**Issue by jbonisteel** [ooni/probe-multiplatform#262]
After experiencing #261 I am also noticing this funky UI glitch, particularly when tapping around the settings section. I have including a screen recording. You can see this sort of, zoom out effect (not sure what else to call it) along the top header of the app. 

https://photos.app.goo.gl/y2XkX2kZYcK6ifkP6

**Comment by sdsantos** [comment]
That's a current Android bug that hasn't been resolved: https://issuetracker.google.com/issues/339835189
But we can find ways of minimising it's effect in the meantime.
