### ISSUE TITLE
NMS Android: Autoruns don't start again after settings are changed

### ISSUE THREAD

**Issue by jbonisteel** [ooni/probe-multiplatform#263]
This is similar to what I see on iOS: https://github.com/ooni/probe-multiplatform/issues/230

If I change the autorun settings (disable 'only while charging'), and then re-enable 'only while charging' + plug phone in - autoruns never seem to start again.

Worth noting - it is possible this is sort of an edge case, I don't know how many people really change those settings that often

**Comment by sdsantos** [comment]
@jbonisteel does it never run again, or does it only start much later? I believe right now, if you change auto-run settings, we set an initial delay of 1 hour before it runs again. So changing the settings might delay an auto-run that would run sooner. That's something we can tweak.

But if it never runs again, then that's a bug we haven't seen before.

**Comment by sdsantos** [comment]
@aanorbel I've investigate this issue using the Background Task Inspector (https://developer.android.com/studio/inspect/task) and everything looks OK. Any idea what else could be happening here?

**Comment by jbonisteel** [comment]
I have been testing this again this afternoon and it does look like auto runs are working more consistently on Android. 

- I tested disabling 'only while charging' and can confirm autoruns do seem to happen now even if not charging
- I re-enabled 'only while charging' and can confirm they have started again once I plugged in my device. 

So not sure if we changed anything but it seems better now.

**Comment by sdsantos** [comment]
@jbonisteel should we close this for now?

**Comment by jbonisteel** [comment]
Yes, we can close
